# Tutorial 07: 
# Regression dengan KNN (K Nearest Neighbours)
- KNN adalah model machine learning yang dapat digunakan untuk melakukan **prediksi berdasarkan kedekatan karakter, dengan sejumlah tetangga terdekat**. 
- Prediksi yang dilakukan dapat **diterapkan baik pada classification maupun regression tasks**. 

### Sample Dataset

In [23]:
import pandas as pd 

sensus = {'tinggi': [158, 170, 183, 191, 155, 163, 180, 158, 170], 
          'jk'    : ['pria', 'pria', 'pria', 'pria', 'wanita', 'wanita', 'wanita', 'wanita', 'wanita'], 
          'berat' : [64, 86, 84, 80, 49, 59, 67, 54, 67]}
          ### Ada 3 keys pada dictionaries ini yaitu tinggi, jenis kelamin, dan berat badan.

sensus_df = pd.DataFrame(sensus)
sensus_df

tinggi      jk  berat
0     158    pria     64
1     170    pria     86
2     183    pria     84
3     191    pria     80
4     155  wanita     49
5     163  wanita     59
6     180  wanita     67
7     158  wanita     54
8     170  wanita     67

### Regression dengan KNN
Di tahap ini **variable features yang dipakai adalah data dari tinggi dan jenis kelamin**, sedangkan **variable target** yang dipakai adalah **berat**. Oleh karena itu, kita mencoba untuk **memprediksi nilai (berat badan) yang mana bersifat cointinues dengan menggunakan Regresi pada KNN**. 
#### Features dan Target

In [24]:
import numpy as np 

x_train = np.array(sensus_df[['tinggi', 'jk']]) # Konversi data frame menjadi array pada features variable
y_train = np.array(sensus_df['berat'])          # Konversi data frame menjadi array pada target variable

print(f'x train: {x_train}')
print(f'y train: {y_train}')

x train: [[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [170 'wanita']]
y train: [64 86 84 80 49 59 67 54 67]


#### Preprocess Dataset: Konversi Label Menjadi Numerik Biner

In [25]:
x_train_transposed = np.transpose(x_train)

print(f'x train: {x_train}')
print(f'x train: {x_train_transposed}') # Merubah posisi kolom menjadi baris, dan baris menjadi kolom

x train: [[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [170 'wanita']]
x train: [[158 170 183 191 155 163 180 158 170]
 ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita'
  'wanita']]


In [26]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()

jk_binarized = lb.fit_transform(x_train_transposed[1]) # Kita merubah data string di jenis kelamin menjadi biner
jk_binarized = jk_binarized.flatten() # Merubah menjadi 1 dimensi

print(f'jk: {x_train_transposed}')
print(f'jk_binarized: {jk_binarized}')

jk: [[158 170 183 191 155 163 180 158 170]
 ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita'
  'wanita']]
jk_binarized: [0 0 0 0 1 1 1 1 1]


In [27]:
# Memasukan data biner atas jenis kelamin pada x train 

x_train_transposed[1] = jk_binarized
x_train = x_train_transposed.transpose()
x_train

array([[158, 0],
       [170, 0],
       [183, 0],
       [191, 0],
       [155, 1],
       [163, 1],
       [180, 1],
       [158, 1],
       [170, 1]], dtype=object)

### Training KNN Regression Model

In [29]:
from sklearn.neighbors import KNeighborsRegressor 

K = 3 # Jumlah tetangga yang akan digunakan dalam proses regresi
model = KNeighborsRegressor(n_neighbors=K)
model.fit(x_train, y_train) # Training model atas data training yaitu x_train dan y_train

KNeighborsRegressor(n_neighbors=3)

### Prediksi Berat Badan 

In [37]:
x_new = np.array([[155,1]])
x_new

array([[155,   1]])

In [38]:
y_pred = model.predict(x_new)
y_pred

array([55.66666667])