# Tutorial 23
## Pengunaan Indeks dan Slicing di NumPy pada Python

In [1]:
import numpy as np 

In [2]:
# Bilangan distribusi uniform (0-1)
np.random.rand(7)

array([0.79501704, 0.08391192, 0.61697096, 0.46464932, 0.38015548,
       0.81255373, 0.49093229])

In [3]:
# Bilangan distribusi uniform (0-1) dalam bentuk matriks 2 dimensi
np.random.rand(5,4)

array([[0.75158307, 0.09915483, 0.8991469 , 0.49555719],
       [0.48005975, 0.7616762 , 0.3206586 , 0.60065583],
       [0.09249407, 0.82316669, 0.51921795, 0.60757691],
       [0.72332817, 0.45409897, 0.64329346, 0.68202569],
       [0.94663691, 0.48833446, 0.05615422, 0.50047173]])

In [4]:
# Bilangan distribusi normal (Gaussian) 
np.random.randn(10)

array([-0.91308474, -0.19219885,  0.37276898, -1.38493755,  1.07348932,
        1.61972144,  2.03326787,  0.15833472,  0.89917124, -2.10262604])

In [17]:
# Bilangan distribusi normal (Gaussian) dalam bentuk matriks 2 dimensi
np.random.randn(4,4)

array([[-0.0410478 , -0.44037266,  1.9117964 , -0.38305649],
       [ 0.7236337 , -0.74705189,  0.01701785,  0.56123695],
       [-0.40333112, -0.4912706 ,  0.03733762, -1.06474067],
       [-0.60576189,  1.80612763, -0.07723262, -0.78310435]])

**Distribusi Normal** dapat didefinisikan sebagai deretan angka yang berada pada nilai negatif sampai dengan positif, di python distribusi ini dituliskan sebaga **randn**. Sedangkan **Distribusi Uniform** didefinisikan deretan angka yang berada pada nilai positif saja, dan dituliskan sebagai **rand**. 

Untuk menggunakannya harus **import numpy dengan fungsi rand, randn, dan randint** sebagai berikut. 

In [8]:
from numpy.random import randn, randint

In [7]:
randn(6,2)

array([[ 0.8666995 ,  0.49522742],
       [ 1.86676276,  3.5911451 ],
       [-1.00773703, -0.51752215],
       [-1.02663101, -1.46231071],
       [-0.60316197, -1.5265515 ],
       [ 1.80873655,  0.21554724]])

In [9]:
randint(0,10)

8

In [11]:
randint(0,10,5)

array([1, 2, 4, 5, 5])

In [14]:
bilangan = randint(0,100,20)
bilangan

array([10, 10, 96, 51, 93, 80, 66, 31, 80, 91, 86, 55, 77, 19, 45, 52,  6,
       96, 21, 68])

In [15]:
bilangan.reshape(4,5)

array([[10, 10, 96, 51, 93],
       [80, 66, 31, 80, 91],
       [86, 55, 77, 19, 45],
       [52,  6, 96, 21, 68]])

Contoh di atas merupakan **cara untuk merubah list array menjadi list matriks** dengan menggunakan **mehtods reshape**. Perlu diperhatikan bahwa **perkalian antara kolom dan baris** harus **sama dengan jumlah data (n)** yang terdapat pada satu variabel. 

In [21]:
coba = randint (0,10,20).reshape(4,5)
coba

array([[5, 1, 1, 3, 8],
       [7, 5, 6, 8, 7],
       [9, 5, 2, 7, 2],
       [8, 2, 3, 6, 0]])

In [22]:
coba = coba.reshape(2,10)
coba

array([[5, 1, 1, 3, 8, 7, 5, 6, 8, 7],
       [9, 5, 2, 7, 2, 8, 2, 3, 6, 0]])

In [34]:
Matriks1D = randint(0,100,20 )
Matriks1D

array([29,  4, 13, 57, 54, 79, 61, 73, 68, 89, 53, 37, 24, 48, 91, 14, 35,
       81, 36, 72])

In [36]:
print(Matriks1D.max())
print(Matriks1D.min())
print(Matriks1D.mean())


91
4
50.9


In [27]:
Matriks2D = randint (0,100,20).reshape(4,5)
Matriks2D

array([[67,  7, 19, 16,  0],
       [57, 36, 92, 90, 30],
       [56, 19, 28, 87, 80],
       [89, 60, 79, 50, 28]])

In [37]:
print(Matriks2D.max())
print(Matriks2D.min())
print(Matriks2D.mean())

92
0
49.5


### Penggunaan Indexing di NumPy pada Python


Pada **NumPy** variabel dibawah dimana **coba2 = coba[0:6] bersifat mengikat 2 arah**, sehingga ketika **kita merubah value dari coba2, maka data di coba 1 juga akan berubah**. Hal ini juga berlaku pada sebaliknya. Contoh penggunannya adalah sebagai berikut:

**Contoh 1:**

In [57]:
import numpy as np

In [70]:
coba = np.arange (0,11)
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
coba[3]

3

In [72]:
coba[5:10]

array([5, 6, 7, 8, 9])

In [77]:
coba2 = coba[0:6]
coba2

array([100, 100, 100, 100, 100, 100])

In [75]:
coba2[:] = 100
coba2

array([100, 100, 100, 100, 100, 100])

In [90]:
coba

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

**Contoh 2:**

In [91]:
l = np.arange(10,16)
l

array([10, 11, 12, 13, 14, 15])

In [92]:
m = ab[3:5]
m 

array([50, 50])

In [93]:
m[:] = 50
m

array([50, 50])

In [94]:
l

array([10, 11, 12, 13, 14, 15])

Apabila kedua **variabel diinginkan untuk berdiri secara independen dan tidak terikat satu sama lain**, maka pada fungsi persamaan array **harus ditambahkan method .copy()**. Contoh penggunannnya adalah sebagai berikut: 

In [101]:
x = np.array ([100, 200, 300, 400, 500])
x

array([100, 200, 300, 400, 500])

In [102]:
y = x[1:4].copy()
y

array([200, 300, 400])

In [103]:
y[1:2] = 50 
y

array([200,  50, 400])

In [104]:
x 

array([100, 200, 300, 400, 500])

### Indexing Matriks NumPy pada Python

In [129]:
matriks_1 = np.array ([[1,2,3,4,5] , [6,7,8,9,10] , [11,12,13,14,15] , [16,17,18,19,20] , [21,22,23,24,25] , [26,27,28,29,30]])
matriks_1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

Contoh **indexing pada matriks di NumPy**, dimana penulisannya adalah
**matriks_1 [baris_awal:baris_akhir , kolom_awal:kolom_akhir]**

In [130]:
matriks_1[0][0]

1

In [131]:
matriks_1[2:3, 0:2]

array([[11, 12]])

In [132]:
matriks_1[3: , 2: ]

array([[18, 19, 20],
       [23, 24, 25],
       [28, 29, 30]])

In [133]:
matriks_2 = matriks_1 [ :3 , 2:].copy()
matriks_2

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

In [134]:
matriks_2[1: , 1: ] = 100
matriks_2

array([[  3,   4,   5],
       [  8, 100, 100],
       [ 13, 100, 100]])

In [135]:
matriks_1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

## Slicing Boolean di Numpy pada Python

In [150]:
import numpy as np

**Contoh 1:**

In [151]:
bil = np.arange(1,11)
bil

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [152]:
angkaT = bil>5
angkaT

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [153]:
bil = bil[angkaT]
bil

array([ 6,  7,  8,  9, 10])

**Contoh 2:**

In [154]:
bil2 = np.array([10,20,30,40,50])
bil2

array([10, 20, 30, 40, 50])

In [155]:
bil2 = bil2 [bil2>30]
bil2

array([40, 50])