# Tutorial 22 

## Pengunaan Library NumPy pada Python

In [1]:
import numpy as np 

In [2]:
angka = [1,2,3]

In [3]:
angkanp = np.array(angka)

In [10]:
angkanp

array([1, 2, 3])

Salah satu perbedaan yang terdapat antara **array dan list yang berisikan integer adalah pada proses aritmatika**. Ketika kita **mengkalikan 2x list integer** maka hasilnya adalah **setiap elemen di list tersebut dituliskan sebanyak 2 kali**. Namun apabila kita **mengkalikan 2x pada array** maka hasilnya adalah **nilai setiap elemen tersebut dikalikan 2.**. Hal ini ditunjukan sebagai berikut: 

In [5]:
angka*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [11]:
angkanp*3

array([3, 6, 9])

fungsi **np.array** juga dapat merubah **nested list** menjadi matriks, sebagai berikut: 

In [7]:
versilist = [[1,2,3] , [4,5,6] , [7,8,9]] 
versilist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
versinumpy = np.array(versilist)

In [9]:
versinumpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

cara **membangkitkan angka 0** pada python dapat dilakukan dengpan menggunakan **np.zeros()**, sedangkan **angka 1** diwakilkan dengan **np.ones** seperti pada contoh di bawah ini

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.ones(3)

array([1., 1., 1.])

cara **membuat matriks** pada python dengan menggunakan array juga dapat dilakukan dengan **mengkombinasikan tuple pada array**, sebagai contoh **np.zeros ((a,b))** dimana **a adalah baris dan b adalah kolom**, seperti yang dicontohkan di bawah ini:

In [21]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

fungsi dari **np.linspace(a,b,c)** adalah untuk menuliskan array yang berisikan **angka dimulai dari a sampai dengan b dengan pecahan c**. Perbedaannya dengan *np.arange (a,b,c)* adalah pada fungsi arrange, **nilai b tidak diperhitungkan**.  

In [27]:
np.linspace(0,8,10) 

array([0.        , 0.88888889, 1.77777778, 2.66666667, 3.55555556,
       4.44444444, 5.33333333, 6.22222222, 7.11111111, 8.        ])

## Cara Identifikasi Matriks pada Python

**Matriks Identitas / Satuan / Eye** pada Python dapat dituliskan dengan menggunakan **np.eye(a)**, dimana **a** merepresentasikan **jumlah kolom** yang terdapat pada matriks identitas tersebut. Semua matriks yang dikalikan dengan **np.eye(a)** nilainya tidak akan berubah. 

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])