# Tutorial 24
## Operasi Matematik di NumPy pada Python

In [1]:
import numpy as np 

In [3]:
coba = np.arange(0,11)

In [4]:
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
coba+coba

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
coba*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
coba_list = [0,1,2,3,4,5,6,7,8,9,10]

In [9]:
coba_list+coba_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [10]:
coba-coba

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.exp(coba)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [12]:
coba.max()

10

In [14]:
coba.min()

0

In [15]:
np.sin(coba)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])